# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd50486e04a65f1c90ad972ba4ad32dac8b6560e3d0669bf5c6f8a190b9620446fc2a13ab5b780990ecdcea0963adac347fc6b93bc4091f4fecd8308fe36d38d

test:
  secret_key_base: 56e50d9da7f8b3930a284d7c953d4d46cd3d717da6360ce7d5134c3c97d015fe76ea2a409155b5202beb139fe318a3592344ceb5a0512529412c8cf4381d1e85

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
